project/blog/urls.py
from django.urls import path
from blog import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/',views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from blog.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', post_list),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sign_up/', sign_up)

]

# Добавляем поддержку медиа-файлов в режиме отладки
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone # часовые пояса
from taggit.managers import TaggableManager


# Create your models here.
class Author(models.Model):
    id = models.AutoField(primary_key=True)  
    username = models.CharField(max_length=15, unique=True)
    age = models.IntegerField()
    email = models.EmailField(unique=True)  
    password = models.CharField(max_length=128) 
    
    def __str__(self):
        return self.username
    


class PublishedManager(models.Manager):
    def get_queryset(self) -> models.QuerySet:
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (('draft', 'Draft'), ('published', 'Published'),)
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField(max_length=2000)
    publish = models.DateField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    image = models.ImageField(upload_to='post_images/', blank=True, null=True)
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, 
                                                 self.publish.month, self.publish.day, self.slug])


    class Meta: # порядок сортировки статей
        ordering = ('-publish',)
    def __str__(self):
        return self.title 



class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created', )

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'
    

project/blog/forms.py
from django import forms
from .models import Comment, Author

class RegistrationForm(forms.Form):
    username = forms.CharField()
    age = forms.IntegerField()
    email = forms.EmailField()
    password = forms.CharField()
    repeat_password = forms.CharField()
    

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)
        
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

project/blog/views.py
from pyexpat.errors import messages
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.core.mail import send_mail
from django.contrib import messages
from taggit.models import Tag
from django.db.models import Count 
from .models import Post, Comment, Author
from .forms import EmailPostForm, CommentForm, RegistrationForm
from django.utils import timezone

# Create your views here.

# функция пагинатора для отображения статей
def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags=tag)

    try:
        items_per_page = int(request.GET.get('items_per_page', 4))
    except ValueError:
        items_per_page = 4  

    paginator = Paginator(object_list.order_by('id'), items_per_page)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    if not page.object_list:
        messages.info(request, 'No posts available')

    context = {
        'posts': page.object_list,  # Передаем только объекты текущей страницы
        'page': page,                # Передаем сам объект страницы
        'request': request,
        'tag': tag
    }
    
    return render(request, 'blog/list.html', context)



# отображение деталей поста
def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year,
                             publish__month=month, publish__day=day)
    comments = post.comments.filter(active=True)
    new_comment = None
    comment_form = CommentForm(initial={
        'name': request.user.username,  
        'email': request.user.email     
    }) 
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()

    post_tags_ibs = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ibs).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    context = {
        'post': post,
        'comments': comments, 
        'new_comment': new_comment,
        'comment_form': comment_form,
        'similar_posts': similar_posts  
    }

    return render(request, 'blog/detail.html', context)


# функция отправки постов
def post_share(request, post_id):
    # получение статьи по id
    post = get_object_or_404(Post, id=post_id, status='published')
    form = EmailPostForm(initial={
        'name': request.user.username,  
        'email': request.user.email     
    })
    sent = False
    context = {
            'post': post,
            'form': form,
            'sent': sent
        }

    if request.method == 'POST':
        form = EmailPostForm(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            # отправка поста
            post_url = request.build_absolute_uri(post.get_absolute_url())  
            subject = f"{cd['name']} ({cd['email']}) recommends you reading '{post.title}'"
            message = f'Read "{post.title}" at {post_url}\n\n{cd["name"]}\'s comments:\n{cd["comments"]}' 
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
        else:
            form = EmailPostForm()
        
    return render(request, 'blog/share.html', context)


# функции для регистрации пользователей   
def sign_up(request):
    users = Author.objects.all()
    info = {}
    context = {
        'info':info,
        'users':users
     }
    if request.method == 'POST':
        form = RegistrationForm(request.POST)

        if form.is_valid():
            username = request.POST.get('username')
            age = request.POST.get('age')
            email = request.POST.get('email')
            password = request.POST.get('password')
            repeat_password = request.POST.get('repeat_password')
            

            if password != repeat_password:
                info['error'] = 'Пароли не совпадают'
                return render(request, 'blog/registration.html', context)
            elif int(age) < 18:
                info['error'] = 'Вы несовершеннолетний'
                return render(request, 'blog/registration.html', context)
            elif Author.objects.filter(username=username).exists():
                info['error'] = 'Такой пользователь уже существует'
                return render(request, 'blog/registration.html', context)
            else:
                Author.objects.create(username=username, age=age, email=email, password=password)
                info['error'] = "Регистрация прошла успешно!"
                return render(request, 'blog/registration.html', context)
            
                
    else:
        form = RegistrationForm()  

    return render(request, 'blog/registration.html', context)

project/templates/blog/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Post</title>
        <link rel="stylesheet" type="text/css" href="{% static 'list.css' %}">
    </head>
<body>
    <h1>Post</h1>

    <a class='button' href="http://127.0.0.1:8000/sign_up/">Регистрация</a>
    <a class='button' href="http://127.0.0.1:8000/admin/">Панель администрации</a>
    <a class='button' href="http://127.0.0.1:8000/blog/">Блог</a>
    <h1></h1>
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    
    {% if post.image %}
    <img src="{{ post.image.url }}" alt="{{ post.title }}" />
    {% endif %}
    <h1></h1>
    {{ post.body | linebreaks }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">Share this post</a>
    </p>
    
    <p class="tags">Tags:
        {% for tag in post.tags.all %}
            <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                {{ tag.name }}
            </a>{% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>

    {% with comments.count as total_comments %}
        <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet</p>
    {% endfor %}

    {% if new_comment %}
        <h2>Your comment has been added</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form action="." method="post">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}

    <h2>Recommended Articles</h2>
    {% if similar_posts %}
        <ul>
            {% for similar_post in similar_posts %}
                <li>
                    <a href="{{ similar_post.get_absolute_url }}">{{ similar_post.title }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No recommended articles available</p>
    {% endif %}
</body>
</html>

project/templates/blog/list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Blog</title>
    <link rel="stylesheet" type="text/css" href="{% static 'list.css' %}">
</head>
<body>
    <h1>Posts</h1>

    <a class='button' href="http://127.0.0.1:8000/sign_up/">Регистрация</a>
    <a class='button' href="http://127.0.0.1:8000/admin/">Панель администрации</a>
    <h1></h1>
    {% for post in posts %}
        {% if post.image %}
        <img src="{{ post.image.url }}" alt="{{ post.title }}" />
        {% endif %}
        <h2 class="post-title">
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
        <p class="tags">Tags: {{ post.tags.all|join:", " }}</p>  
        <p class="date">Published {{ post.publish }} by {{ post.author }}</p>  
        <p>{{ post.body|truncatewords:30|linebreaks }}</p>
    {% empty %}
        <p>No posts available.</p>  
    {% endfor %}
    {% include 'blog/paginator.html' with page=page %} 
</body>
</html>

project/templates/blog/paginator.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page=1{% if request.GET.items_per_page %}&items_per_page={{ request.GET.items_per_page }}{% endif %}">&laquo; Первая</a>
            <a href="?page={{ page.previous_page_number }}{% if request.GET.items_per_page %}&items_per_page={{ request.GET.items_per_page }}{% endif %}">Предыдущая</a>
        {% endif %}
        <span class="current">Страница {{ page.number }} из {{ page.paginator.num_pages }}.</span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}{% if request.GET.items_per_page %}&items_per_page={{ request.GET.items_per_page }}{% endif %}">Следующая</a>
            <a href="?page={{ page.paginator.num_pages }}{% if request.GET.items_per_page %}&items_per_page={{ request.GET.items_per_page }}{% endif %}">Последняя &raquo;</a>
        {% endif %}
    </span>
</div>

project/templates/blog/registration.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration</title>
    <link rel="stylesheet" type="text/css" href="{% static 'registration.css' %}">
</head>
<body>

    <h1>Registration</h1>

    <a class='button' href="http://127.0.0.1:8000/blog/">Статьи</a>
    <a class='button' href="http://127.0.0.1:8000/admin/">Админ</a>

    
    {% if info.error %}
        <div class="error-message">
            <h3>Ошибка</h3>
            <h3>{{ info.error }}</h3>
        </div>
    {% endif %}
    
    
    <form method="post">
        {% csrf_token %}
        <h2></h2>
        <label for="username">Введите логин</label>
        <input type="text" id="username" name="username" maxlength="10" required>
        <h5></h5>
        <label for="age">Введите свой возраст</label>
        <input type="number" id="age" name="age" max="100" required>
        <h5></h5>
        <label for="email">Введите свой email</label>
        <input type="text" id="email" name="email" maxlength="100" required>
        <h5></h5>
        <label for="password">Введите пароль</label>
        <input type="password" id="password" name="password" minlength="6" required>
        <h5></h5>
        <label for="repeat_password">Повторите пароль</label>
        <input type="password" id="repeat_password" name="repeat_password" minlength="6" required>
        
        <input type="submit" value="Зарегистрироваться">
    </form>

    
</body>
</html>

project/templates/blog/share.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Share</title>
        <link rel="stylesheet" type="text/css" href="{% static 'registration.css' %}">
    </head>
    <body>
    
        <h1>Share</h1>
    
        <a class='button' href="http://127.0.0.1:8000/blog/">Статьи</a>
        <a class='button' href="http://127.0.0.1:8000/admin/">Админ</a>
        <h1></h1>
        {% if sent %}
            <div class="alert alert-success">
                Ваше сообщение успешно отправлено!
            </div>
        {% else %}
        <form method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
        
            <div>
                <label for="{{ form.name.id_for_label }}">Name:</label>
                {{ form.name }}
                {{ form.name.errors }}
            </div>
        
            <div>
                <label for="{{ form.email.id_for_label }}">Email:</label>
                {{ form.email }}
                {{ form.email.errors }}
            </div>

            <div>
                <label for="{{ form.email.id_for_label }}">To:</label>
                {{ form.to }}
                {{ form.to.errors }}
            </div>
        
            <div>
                <label for="{{ form.comments.id_for_label }}">Comments:</label>
                {{ form.comments }}
                {{ form.comments.errors }}
            </div>
        
            <button type="submit">Share</button>
        </form>
        
        {% endif %}
</body>
</html>